# Generated by Django 3.2.7 on 2021-09-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('Hybrid', 'HYBRID')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapi.make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapi.models'),
        ),
        migrations.AlterField(
            model_name='car',
            name='submodel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapi.submodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'AUTOMATIC'), ('Manual', 'MANUAL')], default='Automatic', max_length=20),
        ),
    ]
